name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Prepare Git environment
      run: |
        git config --global user.email "misha@myrt.co"
        git config --global user.name "mishamyrt"
    
    - name: Test
      run: make test